### PR TITLE
Create Bitbucket Build Status Update docker image and Codefresh step

### PR DESCRIPTION
**Pull request by ydemetriades**
Codefresh step for updating the build status of Bitbucket.

Useful for Merge Checks, CI, reviewing etc.

### CODE REVIEW

**Comment by ydemetriades** [comment]
@olegsu I am pinging you just because you were the person with most contibution
Can you please review this pull request or assign the responsible reviewers?
Thanks!

**Comment by olegsu** [comment]
Hey @ydemetriades,
Thanks for the PR, unfortunately, we do not accept today a new step into this repository, as those steps are managed by Codefresh.
Since the documentation is not ready yet for yet,I would like to help you to make you step published and visible in [Codefresh marketplace](https://codefresh.io/steps).
In the end, publishing a new step is just to change the name, in `step.yaml`, from `bitbucket-buildstatus` to be `[YOUR_ACCOUNT]/bitbucket-buildstatus` and than running Codefresh CLI
`codefresh create -f step.yaml`

**Comment by ydemetriades** [comment]
@olegsu Thanks for the quick reply!
I have already uploaded the step ydemetriades/bitbucket-buildstatus on Codefresh step marketplace.
Thanks for letting me know about the repository intentions.

**Comment by kostis-codefresh** [comment]
Hey @ydemetriades 

We also have now complete docs for the whole process. https://codefresh.io/docs/docs/codefresh-yaml/steps/#creating-a-typed-codefresh-plugin

**Pull request closed without merging**
