### PR TITLE
Sa 83 google scanning

### PR DESCRIPTION
**Pull request by dustinvanbuskirk**
Need a review to publish this step.

### CODE REVIEW

**Comment by dustinvanbuskirk** [comment]
[Google Artifacts Docker image scanning](https://trello.com/c/7J99wArJ/83-google-artifacts-docker-image-scanning)

**Comment by ahromis** [comment]
@dustinvanbuskirk do you have a link to the build for this?

**Review by TedSpinks — APPROVED** [review]
This looks awesome! Love how readable your code is.

**Comment by dustinvanbuskirk** [comment]
@ahromis 

Account: codefreshdemo
Build: https://g.codefresh.io/build/610467f0222c8ec9d4c70866?step=DockerImageScan&tab=output&logs=terminal

**Review by ahromis — APPROVED** [review]
Looks great!

**Pull request merged**
